"""
NJN PPAP Comparator — core logic (importable by app.py or run standalone).
"""

import shutil, os, sys, glob
from datetime import datetime, date
import openpyxl
from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
from openpyxl.comments import Comment

FILL_CHANGED = PatternFill("solid", fgColor="FF8C00")
FILL_ADDED   = PatternFill("solid", fgColor="70AD47")
FILL_REMOVED = PatternFill("solid", fgColor="FF0000")
FONT_REMOVED = Font(name="Century Gothic", size=11, color="FFFFFF", strike=True)
FONT_ADDED   = Font(name="Century Gothic", size=11, color="FFFFFF")

FILL_LEGEND_TITLE = PatternFill("solid", fgColor="1F3864")
FILL_LEGEND_CHG   = PatternFill("solid", fgColor="FF8C00")
FILL_LEGEND_ADD   = PatternFill("solid", fgColor="70AD47")
FILL_LEGEND_DEL   = PatternFill("solid", fgColor="FF0000")
FILL_LEGEND_SAME  = PatternFill("solid", fgColor="F2F2F2")


def fmt(val):
    if val is None:
        return ""
    if isinstance(val, (datetime, date)):
        return val.strftime("%Y-%m-%d")
    return str(val).strip()


def read_values(path):
    """Returns string values for comparison AND raw values for output population."""
    wb = openpyxl.load_workbook(path, data_only=True)
    ws = wb["NJN"]
    str_vals = {}
    raw_vals = {}
    for row in ws.iter_rows():
        for cell in row:
            str_vals[(cell.row, cell.column)] = fmt(cell.value)
            raw_vals[(cell.row, cell.column)] = cell.value
    return str_vals, raw_vals, ws.max_row, ws.max_column


def add_legend(ws, start_row, label_a, label_b):
    thin = Side(style="thin", color="AAAAAA")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)
    r = start_row + 1

    ws.merge_cells(start_row=r, start_column=1, end_row=r, end_column=5)
    c = ws.cell(r, 1, f"COMPARISON LEGEND  ·  {label_a}  →  {label_b}")
    c.fill = FILL_LEGEND_TITLE
    c.font = Font(name="Century Gothic", size=11, bold=True, color="FFFFFF")
    c.alignment = Alignment(horizontal="left", vertical="center")
    c.border = border
    ws.row_dimensions[r].height = 20
    r += 1

    for fill, color_name, desc in [
        (FILL_LEGEND_CHG,  "ORANGE", "Cell changed — hover the cell to see the previous value"),
        (FILL_LEGEND_ADD,  "GREEN",  "Row is NEW in this revision"),
        (FILL_LEGEND_DEL,  "RED",    "Row was REMOVED (appended below)"),
        (FILL_LEGEND_SAME, "—",      "No change"),
    ]:
        ws.row_dimensions[r].height = 18
        ws.merge_cells(start_row=r, start_column=1, end_row=r, end_column=1)
        s = ws.cell(r, 1, f"  {color_name}")
        s.fill = fill
        s.font = Font(name="Century Gothic", size=10, bold=True,
                      color="FFFFFF" if color_name != "—" else "444444")
        s.alignment = Alignment(vertical="center")
        s.border = border
        ws.merge_cells(start_row=r, start_column=2, end_row=r, end_column=5)
        d = ws.cell(r, 2, desc)
        d.font = Font(name="Century Gothic", size=10, color="222222")
        d.alignment = Alignment(vertical="center")
        d.border = border
        r += 1

    ws.merge_cells(start_row=r, start_column=1, end_row=r, end_column=5)
    ws.cell(r, 1, f"Generated by NJN Comparator  ·  {datetime.now().strftime('%Y-%m-%d %H:%M')}"
            ).font = Font(name="Century Gothic", size=8, italic=True, color="888888")


def compare_and_export(path_a, path_b, out_path, label_a, label_b):
    """
    Copy path_b to out_path, highlight every cell that differs from path_a.
    Returns (n_changed_cells, n_added_rows, n_removed_rows).
    """
    vals_a, _,     max_row_a, max_col_a = read_values(path_a)
    vals_b, raw_b, max_row_b, max_col_b = read_values(path_b)
    max_row = max(max_row_a, max_row_b)
    max_col = max(max_col_a, max_col_b)

    shutil.copy(path_b, out_path)
    wb = openpyxl.load_workbook(out_path)
    ws = wb["NJN"]

    # ── FIX: openpyxl strips formula cached values when saving, which causes
    # cells with date-format + formula to display as "31-Dec-99" or "0".
    # Solution: replace every formula with its pre-computed value so the
    # output always renders correctly, regardless of viewer. ────────────────
    for (r, c), raw_val in raw_b.items():
        cell = ws.cell(r, c)
        if isinstance(cell.value, str) and cell.value.startswith("="):
            cell.value = raw_val

    n_changed = n_added_rows = n_removed_rows = 0

    for r in range(1, max_row_b + 1):
        has_b = any(vals_b.get((r, c), "") for c in range(1, max_col + 1))
        has_a = any(vals_a.get((r, c), "") for c in range(1, max_col + 1))

        if not has_b:
            continue

        if not has_a:
            n_added_rows += 1
            for c in range(1, max_col + 1):
                if vals_b.get((r, c), ""):
                    ws.cell(r, c).fill = FILL_ADDED
                    ws.cell(r, c).font = FONT_ADDED
            continue

        for c in range(1, max_col + 1):
            va = vals_a.get((r, c), "")
            vb = vals_b.get((r, c), "")
            if va != vb:
                n_changed += 1
                cell = ws.cell(r, c)
                cell.fill = FILL_CHANGED
                try:
                    cell.comment = Comment(
                        f"PREVIOUS ({label_a}):\n{va if va else '(empty)'}",
                        "NJN Comparator", height=60, width=180
                    )
                except Exception:
                    pass

    removed_rows = [
        r for r in range(1, max_row_a + 1)
        if any(vals_a.get((r, c), "") for c in range(1, max_col + 1))
        and not any(vals_b.get((r, c), "") for c in range(1, max_col + 1))
    ]

    append_at = ws.max_row + 2
    if removed_rows:
        n_removed_rows = len(removed_rows)
        ws.merge_cells(start_row=append_at, start_column=1,
                       end_row=append_at, end_column=max_col)
        hdr = ws.cell(append_at, 1,
                      f"ROWS REMOVED in {label_b}  (present in {label_a})")
        hdr.fill = PatternFill("solid", fgColor="8B0000")
        hdr.font = Font(name="Century Gothic", size=11, bold=True, color="FFFFFF")
        hdr.alignment = Alignment(horizontal="left", vertical="center")
        ws.row_dimensions[append_at].height = 20
        append_at += 1
        for src_row in removed_rows:
            ws.row_dimensions[append_at].height = 18
            for c in range(1, max_col + 1):
                val = vals_a.get((src_row, c), "")
                cell = ws.cell(append_at, c, val or None)
                cell.fill = FILL_REMOVED
                cell.font = FONT_REMOVED
            append_at += 1

    add_legend(ws, append_at, label_a, label_b)
    wb.save(out_path)
    return n_changed, n_added_rows, n_removed_rows


def rev_label(path):
    name  = os.path.basename(path).replace(".xlsx", "")
    parts = name.split(" - ")
    rev   = parts[1].strip() if len(parts) > 1 else name
    return rev, f"Rev {rev}"


# ── Standalone CLI ────────────────────────────────────────────────────────────
def main():
    if len(sys.argv) > 1:
        paths = [os.path.expanduser(p) for p in sys.argv[1:]]
    else:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        paths = sorted(glob.glob(os.path.join(script_dir, "*.xlsx")))
        paths = [p for p in paths if "NJN_" not in os.path.basename(p)]

    if not paths:
        print("No .xlsx files found.")
        sys.exit(1)

    files = [(p,) + rev_label(p) for p in paths]
    pairs = [(i, j) for i in range(len(files)) for j in range(i + 1, len(files))]
    stamp = datetime.now().strftime("%Y%m%d_%H%M")
    out_dir = os.path.dirname(os.path.abspath(__file__))

    for i, j in pairs:
        pa, rev_a, lbl_a = files[i]
        pb, rev_b, lbl_b = files[j]
        out = os.path.join(out_dir, f"NJN_{rev_a}_vs_{rev_b}_{stamp}.xlsx")
        n_chg, n_add, n_del = compare_and_export(pa, pb, out, lbl_a, lbl_b)
        print(f"  {lbl_a} → {lbl_b}: {n_chg} changed, {n_add} added, {n_del} removed")
        print(f"  → {out}")
        if sys.platform == "darwin":
            os.system(f'open "{out}"')


if __name__ == "__main__":
    main()
