"""
NJN PPAP Comparator — core logic (importable by app.py or run standalone).
"""

import difflib
import re
import shutil, os, sys, glob
from datetime import datetime, date
import openpyxl
from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
from openpyxl.comments import Comment

FILL_CHANGED = PatternFill("solid", fgColor="ED7D31")
FILL_ADDED   = PatternFill("solid", fgColor="1E7145")
FILL_REMOVED = PatternFill("solid", fgColor="C00000")
FONT_REMOVED = Font(name="Century Gothic", size=11, bold=True, color="FFFFFF", strike=True)
FONT_ADDED   = Font(name="Century Gothic", size=11, bold=True, color="FFFFFF")
FONT_STATUS  = Font(name="Century Gothic", size=11, bold=True, color="FFFFFF")

FILL_LEGEND_TITLE = PatternFill("solid", fgColor="1F3864")
FILL_LEGEND_CHG   = PatternFill("solid", fgColor="ED7D31")
FILL_LEGEND_ADD   = PatternFill("solid", fgColor="1E7145")
FILL_LEGEND_DEL   = PatternFill("solid", fgColor="C00000")
FILL_LEGEND_SAME  = PatternFill("solid", fgColor="F2F2F2")


def fmt(val):
    if val is None:
        return ""
    if isinstance(val, (datetime, date)):
        return val.strftime("%Y-%m-%d")
    return str(val).strip()


def read_values(path):
    """Returns string values for comparison AND raw values for output population."""
    wb = openpyxl.load_workbook(path, data_only=True)
    ws = wb["NJN"]
    str_vals = {}
    raw_vals = {}
    for row in ws.iter_rows():
        for cell in row:
            str_vals[(cell.row, cell.column)] = fmt(cell.value)
            raw_vals[(cell.row, cell.column)] = cell.value
    return str_vals, raw_vals, ws.max_row, ws.max_column


def add_legend(ws, start_row, label_a, label_b, max_col):
    thin = Side(style="thin", color="AAAAAA")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)
    end_col = max_col + 2
    r = start_row + 1

    ws.merge_cells(start_row=r, start_column=1, end_row=r, end_column=end_col)
    c = ws.cell(r, 1, f"COMPARISON LEGEND  ·  {label_a}  →  {label_b}")
    c.fill = FILL_LEGEND_TITLE
    c.font = Font(name="Century Gothic", size=11, bold=True, color="FFFFFF")
    c.alignment = Alignment(horizontal="left", vertical="center")
    c.border = border
    ws.row_dimensions[r].height = 24
    r += 1

    for fill, color_name, desc in [
        (FILL_LEGEND_CHG,  "🟠  CHANGED — cell modified (hover for previous value)", ""),
        (FILL_LEGEND_ADD,  "🟢  ADDED — new row", ""),
        (FILL_LEGEND_DEL,  "🔴  DELETED — row removed", ""),
        (FILL_LEGEND_SAME, "⬜  UNCHANGED", ""),
    ]:
        ws.row_dimensions[r].height = 20
        ws.merge_cells(start_row=r, start_column=1, end_row=r, end_column=end_col)
        s = ws.cell(r, 1, f"  {color_name}")
        s.fill = fill
        s.font = Font(name="Century Gothic", size=10, bold=True,
                      color="FFFFFF" if fill is not FILL_LEGEND_SAME else "444444")
        s.alignment = Alignment(vertical="center")
        s.border = border
        r += 1

    ws.merge_cells(start_row=r, start_column=1, end_row=r, end_column=end_col)
    ws.cell(r, 1, f"Generated by NJN Comparator  ·  {datetime.now().strftime('%Y-%m-%d %H:%M')}"
            ).font = Font(name="Century Gothic", size=8, italic=True, color="888888")


def _row_key(r, data):
    """
    Content-based key so difflib can align rows by meaning, not position.
    Header rows (1-8) match by position; data rows by Part Number;
    footer rows by their label in col A.
    """
    if r <= 8:
        return f"__HDR_{r:03d}"
    pn = (data.get(5) or "").strip()
    if pn:
        level = (data.get(3) or "").strip()
        parent = (data.get(4) or "").strip()
        normalized_parent = parent
        if len(parent) > 5 and parent[-1].isupper() and parent[-2].isalnum():
            normalized_parent = re.sub(r'[A-Z]$', '', parent)
        return f"PART|{level}|{normalized_parent}|{pn}"
    label = (data.get(1) or "").strip()
    if label:
        return f"FOOTER|{label}"
    content = "|".join(str(v) for v in data.values() if v)
    return f"CONTENT|{content}"


def compare_and_export(path_a, path_b, out_path, label_a, label_b):
    """
    Copy path_b to out_path and mark every difference vs path_a:
      - Orange cell  : value changed (hover for previous value)
      - Green row    : row is NEW in path_b
      - Red row      : row was DELETED from path_a — inserted in-place, in order

    Rows are matched by content (Part Number for data rows, label for footer
    rows) using difflib, so the comparison is correct even when rows shift
    position between revisions or documents have very different content.

    Returns (n_changed_cells, n_added_rows, n_removed_rows).
    """
    vals_a, _,     max_row_a, max_col_a = read_values(path_a)
    vals_b, raw_b, max_row_b, max_col_b = read_values(path_b)
    max_col = max(max_col_a, max_col_b)

    # ── Extract non-empty row sequences ──────────────────────────────────────
    def get_rows(vals, max_row):
        out = []
        for r in range(1, max_row + 1):
            data = {c: vals.get((r, c), "") for c in range(1, max_col + 1)}
            if any(data.values()):
                out.append((r, data))
        return out

    rows_a = get_rows(vals_a, max_row_a)
    rows_b = get_rows(vals_b, max_row_b)

    keys_a = [_row_key(r, d) for r, d in rows_a]
    keys_b = [_row_key(r, d) for r, d in rows_b]

    # ── Build ordered operation list via difflib ──────────────────────────────
    # Each entry: ("same"|"added"|"changed"|"deleted", r_b_or_None, data_b_or_None, data_a_or_None)
    sm = difflib.SequenceMatcher(None, keys_a, keys_b, autojunk=False)
    ops = []
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "equal":
            for ia, ib in zip(range(i1, i2), range(j1, j2)):
                ops.append(("same", rows_b[ib][0], rows_b[ib][1], rows_a[ia][1]))
        elif tag == "insert":
            for ib in range(j1, j2):
                ops.append(("added", rows_b[ib][0], rows_b[ib][1], None))
        elif tag == "delete":
            for ia in range(i1, i2):
                ops.append(("deleted", None, None, rows_a[ia][1]))
        elif tag == "replace":
            pairs = min(i2 - i1, j2 - j1)
            for k in range(pairs):
                ops.append(("changed",
                             rows_b[j1 + k][0], rows_b[j1 + k][1],
                             rows_a[i1 + k][1]))
            for ia in range(i1 + pairs, i2):
                ops.append(("deleted", None, None, rows_a[ia][1]))
            for ib in range(j1 + pairs, j2):
                ops.append(("added", rows_b[ib][0], rows_b[ib][1], None))

    # ── Map: which deleted rows go BEFORE which B row ─────────────────────────
    # insertions[b_row_num] = [data_a, ...] to insert before that B row
    # trailing_dels: deleted rows that come after the last B row → append at end
    insertions: dict = {}
    trailing_dels: list = []
    pending: list = []
    for kind, r_b, data_b, data_a in ops:
        if kind == "deleted":
            pending.append(data_a)
        else:
            if pending:
                insertions.setdefault(r_b, []).extend(pending)
                pending = []
    trailing_dels = pending  # anything left after the last B row

    # ── Copy newer file to output ─────────────────────────────────────────────
    shutil.copy(path_b, out_path)
    wb = openpyxl.load_workbook(out_path)
    ws = wb["NJN"]

    # FIX: openpyxl clears formula cached values when saving, making cells
    # with date-format display as "31-Dec-99". Replace formulas with their
    # pre-computed data_only values so the output renders correctly everywhere.
    for (r, c), raw_val in raw_b.items():
        cell = ws.cell(r, c)
        if isinstance(cell.value, str) and cell.value.startswith("="):
            cell.value = raw_val

    # ── Insert deleted rows in-place, bottom→top so row numbers stay valid ────
    n_removed_rows = sum(len(v) for v in insertions.values()) + len(trailing_dels)
    for b_rn in sorted(insertions.keys(), reverse=True):
        data_list = insertions[b_rn]
        # Insert from last→first so the final order matches data_list[0], [1], ...
        for a_data in reversed(data_list):
            try:
                ws.insert_rows(b_rn)
            except Exception:
                pass
            ws.row_dimensions[b_rn].height = 18
            for c in range(1, max_col + 1):
                val = a_data.get(c, "")
                cell = ws.cell(b_rn, c)
                cell.value = val or None
                cell.fill = FILL_REMOVED
                cell.font = FONT_REMOVED
            status = ws.cell(b_rn, max_col + 2, "◄ DELETED")
            status.fill = FILL_REMOVED
            status.font = FONT_STATUS
            status.alignment = Alignment(horizontal="center", vertical="center")

    # How many rows were inserted at or before a given original B row number.
    # Pre-compute a cumulative list and binary-search it (O(log n) per call).
    sorted_ins = sorted(insertions.items())  # [(b_rn, data_list), ...]
    cumulative = []
    total = 0
    for b_rn, dl in sorted_ins:
        total += len(dl)
        cumulative.append((b_rn, total))

    def row_offset(r_b):
        # binary search for last entry with b_rn <= r_b
        lo, hi = 0, len(cumulative)
        while lo < hi:
            mid = (lo + hi) // 2
            if cumulative[mid][0] <= r_b:
                lo = mid + 1
            else:
                hi = mid
        return cumulative[lo - 1][1] if lo > 0 else 0

    # ── Apply highlights (green / orange) with corrected row positions ────────
    n_changed = n_added_rows = 0
    for kind, r_b, data_b, data_a in ops:
        if kind == "deleted":
            continue
        r_adj = r_b + row_offset(r_b)  # shift down past any insertions above

        if kind == "added":
            n_added_rows += 1
            for c, vb in data_b.items():
                if vb:
                    ws.cell(r_adj, c).fill = FILL_ADDED
                    ws.cell(r_adj, c).font = FONT_ADDED
            status = ws.cell(r_adj, max_col + 2, "▲ ADDED")
            status.fill = FILL_ADDED
            status.font = FONT_STATUS
            status.alignment = Alignment(horizontal="center", vertical="center")

        elif kind in ("same", "changed"):
            for c in range(1, max_col + 1):
                va = data_a.get(c, "")
                vb = data_b.get(c, "")
                if va != vb:
                    n_changed += 1
                    cell = ws.cell(r_adj, c)
                    cell.fill = FILL_CHANGED
                    try:
                        cell.comment = Comment(
                            f"PREVIOUS ({label_a}):\n{va if va else '(empty)'}",
                            "NJN Comparator", height=60, width=180
                        )
                    except Exception:
                        pass

    # ── Append any trailing deleted rows (after last B row) ───────────────────
    append_at = ws.max_row + 2
    if trailing_dels:
        ws.merge_cells(start_row=append_at, start_column=1,
                       end_row=append_at, end_column=max_col)
        hdr = ws.cell(append_at, 1,
                      f"ROWS REMOVED in {label_b}  (present in {label_a})")
        hdr.fill = PatternFill("solid", fgColor="8B0000")
        hdr.font = Font(name="Century Gothic", size=11, bold=True, color="FFFFFF")
        hdr.alignment = Alignment(horizontal="left", vertical="center")
        ws.row_dimensions[append_at].height = 20
        append_at += 1
        for a_data in trailing_dels:
            ws.row_dimensions[append_at].height = 18
            for c in range(1, max_col + 1):
                val = a_data.get(c, "")
                cell = ws.cell(append_at, c, val or None)
                cell.fill = FILL_REMOVED
                cell.font = FONT_REMOVED
            status = ws.cell(append_at, max_col + 2, "◄ DELETED")
            status.fill = FILL_REMOVED
            status.font = FONT_STATUS
            status.alignment = Alignment(horizontal="center", vertical="center")
            append_at += 1

    add_legend(ws, ws.max_row + 2, label_a, label_b, max_col)
    wb.save(out_path)
    return n_changed, n_added_rows, n_removed_rows


def rev_label(path):
    name  = os.path.basename(path).replace(".xlsx", "")
    parts = name.split(" - ")
    rev   = parts[1].strip() if len(parts) > 1 else name
    return rev, f"Rev {rev}"


# ── Standalone CLI ────────────────────────────────────────────────────────────
def main():
    if len(sys.argv) > 1:
        paths = [os.path.expanduser(p) for p in sys.argv[1:]]
    else:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        paths = sorted(glob.glob(os.path.join(script_dir, "*.xlsx")))
        paths = [p for p in paths if "NJN_" not in os.path.basename(p)]

    if not paths:
        print("No .xlsx files found.")
        sys.exit(1)

    files = [(p,) + rev_label(p) for p in paths]
    pairs = [(i, j) for i in range(len(files)) for j in range(i + 1, len(files))]
    stamp = datetime.now().strftime("%Y%m%d_%H%M")
    out_dir = os.path.dirname(os.path.abspath(__file__))

    for i, j in pairs:
        pa, rev_a, lbl_a = files[i]
        pb, rev_b, lbl_b = files[j]
        out = os.path.join(out_dir, f"NJN_{rev_a}_vs_{rev_b}_{stamp}.xlsx")
        n_chg, n_add, n_del = compare_and_export(pa, pb, out, lbl_a, lbl_b)
        print(f"  {lbl_a} → {lbl_b}: {n_chg} changed, {n_add} added, {n_del} removed")
        print(f"  → {out}")
        if sys.platform == "darwin":
            os.system(f'open "{out}"')


if __name__ == "__main__":
    main()
